version: "3.9"

services:
    db:
        image: postgres
        volumes:
            - ./database/init:/docker-entrypoint-initdb.d
            - ./database/db:/var/lib/postgresql/data
        env_file:
            - database.env
    backend:
        build: ./backend
        ports:
            - "8080:8080"
        env_file:
            - database.env
            - openweather.env
        depends_on:
            - db
